In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

df = pd.read_excel("KMeans.xlsx")
print(df)

    X1   X2
0  1.0  1.0
1  1.5  2.0
2  3.0  4.0
3  5.0  7.0
4  3.5  5.0
5  4.5  5.0
6  3.5  4.5

In [ ]:
centroids = df.loc[[0, 3], :].reset_index(drop=True)
centroids

    X1   X2
0  1.0  1.0
1  5.0  7.0

In [ ]:
centroids = df.sample(2)#.reset_index(drop=True)
# # centroids

    X1   X2
1  1.5  2.0
4  3.5  5.0

In [ ]:
df1 = df.copy()

# centroids = df.sample(2).reset_index(drop=True)
# centroids.reset_index(drop=True).to_numpy()
centroids = df.loc[[0, 3], :].reset_index(drop=True)

df1['dist_centroid_1'] = np.linalg.norm(df - centroids.loc[0], axis=1)
df1['dist_centroid_2'] = np.linalg.norm(df - centroids.loc[1], axis=1)
print(df1)

df1['Cluster'] = np.where(df1.dist_centroid_1 <= df1.dist_centroid_2, 1, 2)
print(df1)

df1['PrevCluster'] = np.zeros(len(df))
print(df1)

    X1   X2  dist_centroid_1  dist_centroid_2
0  1.0  1.0         0.000000         7.211103
1  1.5  2.0         1.118034         6.103278
2  3.0  4.0         3.605551         3.605551
3  5.0  7.0         7.211103         0.000000
4  3.5  5.0         4.716991         2.500000
5  4.5  5.0         5.315073         2.061553
6  3.5  4.5         4.301163         2.915476
    X1   X2  dist_centroid_1  dist_centroid_2  Cluster
0  1.0  1.0         0.000000         7.211103        1
1  1.5  2.0         1.118034         6.103278        1
2  3.0  4.0         3.605551         3.605551        1
3  5.0  7.0         7.211103         0.000000        2
4  3.5  5.0         4.716991         2.500000        2
5  4.5  5.0         5.315073         2.061553        2
6  3.5  4.5         4.301163         2.915476        2
    X1   X2  dist_centroid_1  dist_centroid_2  Cluster  PrevCluster
0  1.0  1.0         0.000000         7.211103        1          0.0
1  1.5  2.0         1.118034         6.103278        1          0.0
2  3.0  4.0         3.605551         3.605551        1          0.0
3  5.0  7.0         7.211103         0.000000        2          0.0
4  3.5  5.0         4.716991         2.500000        2          0.0
5  4.5  5.0         5.315073         2.061553        2          0.0
6  3.5  4.5         4.301163         2.915476        2          0.0

In [ ]:
movement = True

while (movement):
    centroids = df1.groupby('Cluster')['X1', 'X2'].mean()
    centroids = centroids.reset_index(drop=True)
    print("Centroids:\n", centroids)

    df1['dist_centroid_1'] = np.linalg.norm(df - centroids.loc[0], axis=1)
    df1['dist_centroid_2'] = np.linalg.norm(df - centroids.loc[1], axis=1)
    df1['PrevCluster'] = df1['Cluster']
    df1['Cluster'] = np.where(df1.dist_centroid_1 <= df1.dist_centroid_2, 1, 2)
    print(df1)
    
    movement = (df1['PrevCluster'] != df1['Cluster']).any()
    
    if (movement):
        print('Data Moved\n')
    else:
        print('No Movement of Data\n')
        
    count = count + 1

itr no: 1
Centroids:
      X1   X2
0  1.25  1.5
1  3.90  5.1
    X1   X2  dist_centroid_1  dist_centroid_2  Cluster  PrevCluster
0  1.0  1.0         0.559017         5.021952        1            1
1  1.5  2.0         0.559017         3.920459        1            1
2  3.0  4.0         3.051639         1.421267        2            2
3  5.0  7.0         6.656763         2.195450        2            2
4  3.5  5.0         4.160829         0.412311        2            2
5  4.5  5.0         4.776243         0.608276        2            2
6  3.5  4.5         3.750000         0.721110        2            2
No Movement of Data

In [ ]:
df1['PrevCluster'] != df1['Cluster']).any()